baseURL: "https://llazza.github.io" 
title: Luca Lazzaro
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 5 
        - name: CV
          url: cv/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Luca Lazzaro
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luca Lazzaro
          subtitle: "I am a PhD Candidate and Research Assistant at the University of Zurich, Chair of Marketing for Social Impact and affiliated with the URPP Social Networks."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            #- name: Papers
            #  url: papers/
            #- name: Data
            #  url: data/
            #- name: Courses
            #  url: courses/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:luca.lazzaro@business.uzh.ch
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=0xQdp6kAAAAJ&hl=it 
        - name: Bluesky
          url: https://bsky.app/profile/llazza.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Luca Lazzaro"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
